#pragma once
 // DO NOT EDIT!!!
 // This file is automatically generated by constant_gen.c

#define OBJ_version_info 14233428092473271022ull
#define OBJ_namespace 10664621421627917522ull
#define OBJ_packet 16258717018856987458ull
#define OBJ_enum 8111184261176688359ull
#define OBJ_enums 2875260240548673106ull
#define OBJ_varint 14214682526098707614ull
#define OBJ_varlong 13098499217202556116ull
#define OBJ_varint_enum 16993515100119901028ull
#define OBJ_string 12771467845454168962ull
#define OBJ_byte 11383051565897835207ull
#define OBJ_Ubyte 7917191334794155440ull
#define OBJ_short 9625071128987924084ull
#define OBJ_Ushort 6104312068048490635ull
#define OBJ_int 7096696477163133823ull
#define OBJ_Uint 12034202585249245706ull
#define OBJ_Ulong 17294614387133775196ull
#define OBJ_long 13542995208720016427ull
#define OBJ_boolean 1781534008560267108ull
#define OBJ_uuid 15771943603194523741ull
#define OBJ_prefixed_byte_array 13014630434240501157ull
#define OBJ_prefixed_array 8601685777738177597ull
#define OBJ_prefixed_optional 7261337864673082035ull
#define OBJ_byte_array 1032323356971315ull
#define OBJ_CONTEXT 10971342052073687254ull
#define OBJ_REMAINING_BYTES 17238451018908655191ull
