name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deps
      run: sudo apt-get install ccache zlib1g-dev
    
    # Does not actually do anything substantial yet, just compile it.
    - name: make
      run: make
